www/app/Http/routes.php
<?php

/**
 * @author    Olivier Parent
 * @copyright Copyright © 2014-2015 Artevelde University College Ghent
 * @license   Apache License, Version 2.0
 */

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

// Landing Page
// ============
Route::get('/', function () {
    return view('landing');
});

// Application Programming Interface Routes
// ========================================
Route::group(
    [
        'prefix' => 'api',
    ],
    function () {
        Debugbar::disable();

        // API version 1
        // -------------
        Route::group(
            [
                'namespace' => 'Api', // namespace StartMeUp\Http\Controllers\Api
                'prefix' => 'v1',
            ],
            function () {
                Route::get('/', function () {
                    $uriRoot = Request::root();

                    return [
                        "${uriRoot} API" => [
                            'version' => 1,
                        ],
                    ];
                });
                Route::get('users/{users}/moods/statistics', [
                    'as' => 'api.v1.users.moods.statistics',
                    'uses' => 'UsersMoodsController@statistics',
                ]);
                Route::options('/', function () {
                    return [
                        'X-CSRF-TOKEN' => csrf_token(),
                    ];
                });
                Route::post('auth', [
                    'as' => 'api.v1.auth',
                    'uses' => 'AuthController@login',
                ]);
                $options = [
                    'except' => [
                        'create',
                        'edit',
                    ],
                ];
                Route::resource('addresses', 'AddressesController', $options);
                Route::resource('companies', 'CompaniesController', $options);
                Route::resource('countries', 'CountriesController', $options);
                Route::resource('goals', 'GoalsController', $options);
                Route::resource('interests', 'InterestsController', $options);
                Route::resource('localities', 'LocalitiesController', $options);
                Route::resource('locations', 'LocationsController', $options);
                Route::resource('regions', 'RegionsController', $options);
                Route::resource('targets/checkbox', 'TargetsCheckboxController', $options);
                Route::resource('targets/recurringcheckbox', 'TargetsRecurringCheckboxController', $options);
                Route::resource('targets/duration', 'TargetsDurationController', $options);
                Route::resource('updates/recurringcheckbox', 'UpdatesRecurringCheckboxController', $options);
                Route::resource('updates/duration', 'UpdatesDurationController', $options);
                Route::resource('users', 'UsersController', $options);
                Route::resource('users.categories', 'UsersCategoriesController', $options);
                Route::resource('users.goals', 'UsersGoalsController', $options);
                Route::resource('users.moods', 'UsersMoodsController', $options);
                Route::resource('users.settings', 'UsersSettingsController', $options);
            }
        );
    }
);

// Back Office Routes
// ==================
Route::group(
    [
        'as' => 'backoffice.',
        'prefix' => 'backoffice',
    ],
    function () {
        Route::get('/', [
            'as' => 'home',
            'uses' => 'BackofficeController@index',
        ]);
    }
);

// Front Office Routes
// ===================
Route::group(
    [
        'as' => 'frontoffice.',
        'prefix' => 'frontoffice',
    ],
    function () {
        Debugbar::disable();
        Route::get('/', [
            'as' => 'home',
            'uses' => 'FrontofficeController@index',
        ]);
    }
);

// Style Guide Routes
// ==================
Route::get('/styleguide', [
    'as' => 'styleguide.home',
    function () {
        Debugbar::disable();

        return view('styleguide');
    },
]);

www/resources/views/backoffice.blade.php
@extends('layouts.backoffice')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Home</div>

				<div class="panel-body">
					<p>You are logged in at {!! Carbon\Carbon::now()->formatLocalized('%H:%M:%S <abbr title="Coordinated Universal Time">UTC</abbr> on %A %d %B %Y') !!}!</p>
					<p style="text-align: center"><img src="{!! asset('images/logo.svg') !!}" width="200"></p>
				</div>
			</div>
		</div>
	</div>
</div>
@stop

www/resources/views/frontoffice.blade.php
@extends('layouts.frontoffice')

@section('content')
<body ng-controller="AppCtrl as app">
	<section layout="row" flex>
		<ng-include src="'templates/sidenav-left.partial.html'"></ng-include>
		<div class="view view-animate-container">
			<ng-view class="view view-animate" autoscroll="true"></ng-view>
		</div>
	</section>
</body>
@stop

www/resources/views/landing.blade.php
@extends('layouts.frontoffice')

@section('content')
<body>
	<md-content class="md-padding" layout="column" layout-align="center center">
		<style>
			section {
				max-width: 60em;
				padding: 1em;
				width: 100%;
			}
			section > h1,
			section > p {
				margin: auto;
				max-width: 30em;
				padding-bottom: 1em;
			}
			section > h1 {
				max-width: 15em;
				width: 100%;
			}
			footer > p {
				text-align: center;
			}
			footer > p > a > img {
				max-width: 15em;
			}
			.md-button + .md-button {
				margin-left: 1em;
			}
		</style>
		<section class="md-whiteframe-z1">

			<h1><a href="{{ URL::route('frontoffice.home') }}"><img src="images/logo_app.svg" alt="startmeupbuddy.io"></a></h1>

			<p>You are a <strong>born entrepreneur</strong>, but sometimes you feel like you are alone in your world? You are looking for <strong>peers</strong>? You are looking for support? You are looking for that extra trigger that keeps it exciting. <strong>Celebrations</strong> to your efforts and <strong>achievements</strong>?</p>

			<p>StartMeUp.io, a <strong>mobile buddy</strong> app will give you these little moments of support and celebration. A personal coach in your venture, it is always there and it gives you support.</p>

			<p>Based on the data you put in, you will receive <strong>feedback loops</strong>. The more you use the app, the better it will get to know you, the better it will support you.</p>

			<h2 class="centered">Co-creation – open source</h2>
			<p>The open source app is in <strong>co-creation</strong> with students, pre- and early stage starters. Once we have a solid prototype we can open it up to the community for further improvements and subject for debate.</p>

			<h2 class="centered">Aim of project</h2>
			<p>The aim of this research project is to test it out among <strong>startup communities</strong> in different regions. The data can be used in research to map entrepreneurial behaviour.</p>

			<p>In addition we see it as tool that can be embedded in the curriculum of students to test their entrepreneurial skills.</p>

			<footer>
				<p><a href="http://www.arteveldehogeschool.be/en"><img src="images/logo_arteveldehogeschool.svg" alt="Artevelde University College Ghent"></a></p>
				<p>©2014-{{ Carbon\Carbon::now()->year }} Christel De Maeyer, Karijn Bonne &amp; Olivier Parent</p>
				<p><img src="images/email_christel.svg" alt="Contact Christel De Maeyer"></p>
			</footer>
		</section>

		<section layout="row" layout-sm="column" layout-align="center center">
			{!! Html::linkRoute('frontoffice.home', 'Web App'    , [], ['class' => 'md-button md-raised md-accent md-default-theme']) !!}
			{!! Html::linkRoute('backoffice.home' , 'Admin'      , [], ['class' => 'md-button md-raised md-default-theme']) !!}
			{!! Html::linkRoute('styleguide.home' , 'Style Guide', [], ['class' => 'md-button md-raised md-default-theme']) !!}
		</section>

	</md-content>
</body>
@stop

www/resources/views/styleguide.blade.php
@extends('layouts.frontoffice')

@section('head-styles')
	@parent
	{!! Html::style('styles/css/styleguide.css') !!}
@stop

@section('head-scripts')
	@parent
	{!! Html::script('scripts/js/styleguide.js') !!}
@stop

@section('content')
<body ng-controller="StyleGuideCtrl as vm" id="style-guide">
	<h1 class="style-guide">StartMeUp Style Guide</h1>
	<p class="style-guide">This is the style guide for the <a href="http://www.startmeupbuddy.io">StartMeUp</a> web app developed at <a href="http://arteveldehogeschool.be/en">Artevelde University College Ghent</a>.</p>

	<md-divider class="style-guide"></md-divider>

	<section>
		<h2 class="style-guide">Headings</h2>
		<div class="style-guide">
			<h1>Heading Level 1</h1>
			<h2>Heading Level 2</h2>
			<h3>Heading Level 3</h3>
			<h4>Heading Level 4</h4>
			<h5>Heading Level 5</h5>
			<h6>Heading Level 6</h6>
		</div>
	</section>

	<md-divider class="style-guide"></md-divider>

	<section>
		<h2 class="style-guide">Paragraphs</h2>
		<div class="style-guide">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae consequatur distinctio ea expedita fugiat libero obcaecati reiciendis reprehenderit? Accusantium consectetur delectus deleniti doloribus eius excepturi magni neque sint sit sunt!</p>
			<p>Adipisci dolorum error officia sint! Nulla, odit, sequi. At autem blanditiis consectetur distinctio, dolorem earum error eveniet facilis fuga illum modi molestias, neque perspiciatis qui quod ratione saepe tenetur ullam?</p>
			<p>Ad aspernatur atque delectus deleniti doloremque earum eligendi fugit impedit ipsa iste molestiae mollitia nemo, nihil non obcaecati officiis omnis optio pariatur perferendis placeat possimus quidem sapiente similique velit voluptatum?</p>
			<p>Lorem ipsum <a href="">dolor sit amet</a>, consectetur adipisicing elit. Ad blanditiis delectus dolores, eligendi excepturi fugiat incidunt ipsum, iure iusto maiores nobis placeat porro quia quod repudiandae similique tempore, tenetur voluptatem!</p>
		</div>
	</section>

	<md-divider class="style-guide"></md-divider>

	<section>
		<h2 class="style-guide">Forms</h2>

		<h3 class="style-guide">Checkboxes</h3>
		<div class="style-guide">
			<form action="" name="styleGuideForm">
				<md-checkbox ng-model="vm.checkboxes.cb0" aria-label="Checkbox">
					Value: @{{ vm.checkboxes.cb0 }}
				</md-checkbox>

				<md-checkbox ng-model="vm.checkboxes.cb1" ng-true-value="'yes'" ng-false-value="'no'" aria-label="Checkbox with custom values">
					Value: @{{ vm.checkboxes.cb1 }}
				</md-checkbox>

				<md-checkbox ng-model="vm.checkboxes.cb2" ng-disabled="true" aria-label="Disabled checkbox">
					Checkbox (Disabled)
				</md-checkbox>

				<md-checkbox ng-model="vm.checkboxes.cb3" ng-init="checkboxes.cb3=true" ng-disabled="true" aria-label="Disabled checked checkbox" >
					Checkbox (Disabled, Checked)
				</md-checkbox>

				<md-checkbox ng-model="vm.checkboxes.cb4" md-no-ink aria-label="Checkbox No Ink">
					Checkbox (No Ink)
				</md-checkbox>
			</form>
		</div>

		<h3 class="style-guide">Radiobuttons</h3>
		<div class="style-guide">
			<form action="" name="styleGuideForm">
				<md-radio-group ng-model="vm.user.gender" layout layout-sm="column">
					<md-radio-button flex value="f" aria-label="female">female</md-radio-button>
					<md-radio-button flex value="m" aria-label="male">male</md-radio-button>
					<md-radio-button flex value="o" aria-label="other">other</md-radio-button>
				</md-radio-group>

				<p>I&rsquo;m a:</p>
				<md-radio-group ng-model="vm.user.role">
					<md-radio-button value="prestarter" aria-label="prestarter">prestarter</md-radio-button>
					<md-radio-button value="starter" aria-label="starter">starter</md-radio-button>
					<md-radio-button value="serial" aria-label="serial entrepreneur" lang="en">serial entrepreneur</md-radio-button>
				</md-radio-group>
			</form>
		</div>

		<h3 class="style-guide">Switches</h3>
		<div class="style-guide">
			<form action="" name="styleGuideForm">
				<div layout layout-sm="column">
					<md-switch flex  ng-model="vm.switches.sw0" ng-true-value="'Yes I do want to collaborate with others'" ng-false-value="'No I don&rsquo;t want to collaborate with others'" aria-label="Switch 1">
						@{{ vm.switches.sw0 }}
					</md-switch>
				</div>
			</form>
		</div>

		<h3 class="style-guide">Selects</h3>
		<div class="style-guide">
			<form action="" name="styleGuideForm">
				<md-select ng-model="vm.goals" placeholder="Categories">
					<md-optgroup label="Category A">
						<md-option ng-value="vm.goal.name" ng-repeat="goal in goals | filter: {category: 'Category A' }">@{{ goal.name }}</md-option>
					</md-optgroup>
					<md-optgroup label="Category B">
						<md-option ng-value="vm.goal.name" ng-repeat="goal in goals | filter: {category: 'Category B' }">@{{ goal.name }}</md-option>
					</md-optgroup>
				</md-select>
			</form>
		</div>

		<h3 class="style-guide">Inputs</h3>
		<div class="style-guide">
			<form action="" name="styleGuideForm">
				<div layout layout-sm="column">
					<md-input-container flex>
						<label>First name</label>
						<input ng-model="vm.user.firstName" name="firstName" required>
						<div ng-messages="styleGuideForm.firstName.$error">
							<div ng-message="required">This field is required.</div>
						</div>
					</md-input-container>
					<md-input-container flex>
						<label>Last name</label>
						<input ng-model="vm.user.lastName" name="lastName" required>
						<div ng-messages="styleGuideForm.lastName.$error">
							<div ng-message="required">Dit veld is verplicht.</div>
						</div>
					</md-input-container>
				</div>

				<md-input-container>
					<label>Birthday</label>
					<input type="date" ng-model="vm.user.birthday">
				</md-input-container>

				<div layout layout-sm="column">
					<md-input-container flex>
						<label>Mobile phone</label>
						<input ng-model="vm.user.mobilePhone">
					</md-input-container>
					<md-switch flex ng-model="vm.switches.sw1" ng-true-value="'public'" ng-false-value="'private'"  aria-label="Switch 1">
						@{{ vm.switches.sw1 }}
					</md-switch>
				</div>

				<div layout layout-sm="column">
					<md-input-container flex>
						<label>Email</label>
						<input ng-model="vm.user.email" type="email">
					</md-input-container>
					<md-switch flex ng-model="vm.switches.sw2" ng-true-value="'public'" ng-false-value="'private'"  aria-label="Switch 1">
						@{{ vm.switches.sw2 }}
					</md-switch>
				</div>

				<!-- http://microformats.org/wiki/h-adr -->

				<div layout layout-sm="column">
					<md-input-container flex>
						<label>Street</label>
						<input ng-model="vm.company.address.street" name="street" required>
					</md-input-container>
				</div>

				<div layout layout-sm="column">
					<md-input-container flex>
						<label>Postal code</label>
						<input ng-model="vm.company.address.postalCode" name="postalCode" required>
					</md-input-container>
					<md-input-container flex>
						<label>Locality</label>
						<input ng-model="vm.company.address.city" name="locality" required>
					</md-input-container>
				</div>

			</form>
		</div>
	</section>

	<md-divider class="style-guide"></md-divider>

	<section>
		<h2 class="style-guide">Progress Bars</h2>
		<div class="style-guide">
			<md-progress-linear md-mode="determinate" value="33"></md-progress-linear>
			<br>
			<md-progress-linear md-mode="determinate" value="66"></md-progress-linear>
			<br>
			<md-progress-linear md-mode="determinate" value="100"></md-progress-linear>
			<br>

			<br>
			<md-progress-linear md-mode="determinate" value="25"></md-progress-linear>
			<br>
			<md-progress-linear md-mode="determinate" value="50"></md-progress-linear>
			<br>
			<md-progress-linear md-mode="determinate" value="75"></md-progress-linear>
			<br>
			<md-progress-linear md-mode="determinate" value="100"></md-progress-linear>
			<br>
		</div>
	</section>

	<md-divider class="style-guide"></md-divider>

	<section>
		<h2 class="style-guide">Charts</h2>
		<div class="style-guide">
			<canvas id="style-guide-chart-0" width="400" height="400"></canvas>
			<canvas id="style-guide-chart-1" width="400" height="400"></canvas>
		</div>
	</section>

	<md-divider class="style-guide"></md-divider>

	<section>
		<h2 class="style-guide">Map</h2>
		<div class="style-guide">
			<div id="style-guide-map-0" class="style-guide-map"></div>
		</div>
	</section>

</body>
@stop